# docker-compose -f docker-compose-dev.yml up --build -d
# docker-compose -f docker-compose-dev.yml down
# docker-compose -f docker-compose-dev.yml up

services:
  bot:
    build: .
    container_name: oi-screener
    command: [ "python", "main.py" ]
    env_file:
      - src/.env
    environment:
      - LOG_LEVEL=debug
      - PYTHONPATH=/usr
    volumes:
      - storage_data:/usr/src/storage
      - logs_data:/usr/src/logs
      - symbols:/usr/src/symbols
    networks:
      - bot_network
    depends_on:
      postgres_db:
        condition: service_healthy

  postgres_db:
    #image: timescale/timescaledb:2.21.3-pg15
    #image: timescale/timescaledb:2.21.3-pg16
    image: timescale/timescaledb:2.21.3-pg17
    container_name: oi-postgres
    restart: always
    environment:
      POSTGRES_DB: screener_db
      POSTGRES_USER: screener_user
      POSTGRES_PASSWORD: screener_pass
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - bot_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h 127.0.0.1 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  storage_data:
  logs_data:
  symbols:
  pg_data:

networks:
  bot_network:
    driver: bridge
