services:
  bot:
    restart: always
    build: .
    container_name: oi-screener
    command: [ "python", "main.py" ]
    env_file:
      - .env
    environment:
      - LOG_LEVEL=debug
      - PYTHONPATH=/usr/src/app
    volumes:
      - ./src:/usr/src/app/src
      - ./storage:/usr/src/app/storage
      - ./logs:/usr/src/app/logs
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge