# docker-compose -f docker-compose-dev.yml up --build
# docker-compose -f docker-compose-dev.yml down
# docker-compose -f docker-compose-dev.yml up
services:
  bot:
    restart: always
    build: .
    container_name: oi-screener
    command: [ "python", "main.py" ]
    env_file:
      - .env
    environment:
      - LOG_LEVEL=debug
      - PYTHONPATH=/usr
    volumes:
      - ./src:/usr/src
      - ./storage:/usr/src/storage
      - ./logs:/usr/src/logs
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge